#!/usr/bin/env ruby

require "pathname"
# add lib folder to load path
$LOAD_PATH << File.join( File.dirname(Pathname.new(__FILE__).realpath), 'lib' )

require "print-char-sheet"
require "json"
require "read-from-db"

hours_worked = 0
drank_water = false
enough_sleep = false
did_workout = false
did_meditation = false
ate_fruit_veg = false
earned_bonus = false

positive = ["da", "DA", "d", "D", "yes", "YES", "y", "Y"]
negative = ["ne", "NE", "n", "N", "no", "NO"]
possible_bool_answers = positive + negative

bonus_coefficient = 0.5
bonuses = {
  1 => "Finished a project",
  2 => "Refactored old code",
  3 => "Finished a milestone"
}
bonus_key = 0
xp_per_hour = 100

if ARGF.argv.empty?
  print_char_sheet(read_from_db)

elsif ARGF.argv.length == 1 && ARGF.argv[0] == "-milestone"
  print "Next milestone: "
  milestone = STDIN.gets.chomp
  data = read_from_db
  data["next_milestone"] = milestone
  File.write("#{File.dirname(Pathname.new(__FILE__).realpath)}/db.txt", JSON.generate(data))
  print_char_sheet(read_from_db)

elsif ARGF.argv.length == 1 && ARGF.argv[0] == "-add"
  loop do
    print "Hours of work today: "
    hours_worked = STDIN.gets.chomp
    break if hours_worked.to_i.to_s == hours_worked && hours_worked.to_i >= 0
    puts "Use positive integer or 0!"
  end
  hours_worked = hours_worked.to_i

  loop do
    print "Drank 1.5L of water? "
    drank_water = STDIN.gets.chomp
    break if positive.include?(drank_water) || negative.include?(drank_water)
    puts "Possible answers: " + possible_bool_answers.to_s
  end
  drank_water = positive.include?(drank_water) ? true : false
  
  loop do
    print "Got at least 8h of sleep? "
    enough_sleep = STDIN.gets.chomp
    break if positive.include?(enough_sleep) || negative.include?(enough_sleep)
    puts "Possible answers: " + possible_bool_answers.to_s
  end
  enough_sleep = positive.include?(enough_sleep) ? true : false

  loop do
    print "Did at least 30min of workout? "
    did_workout = STDIN.gets.chomp
    break if positive.include?(did_workout) || negative.include?(did_workout)
    puts "Possible answers: " + possible_bool_answers.to_s
  end
  did_workout = positive.include?(did_workout) ? true : false

  loop do
    print "Did at least 15min of meditation? "
    did_meditation = STDIN.gets.chomp
    break if positive.include?(did_meditation) || negative.include?(did_meditation)
    puts "Possible answers: " + possible_bool_answers.to_s
  end
  did_meditation = positive.include?(did_meditation) ? true : false

  loop do
    print "Ate enough fruit and vegetables? "
    ate_fruit_veg = STDIN.gets.chomp
    break if positive.include?(ate_fruit_veg) || negative.include?(ate_fruit_veg)
    puts "Possible answers: " + possible_bool_answers.to_s
  end
  ate_fruit_veg = positive.include?(ate_fruit_veg) ? true : false

  loop do
    print "Earned a bonus? (finished project, refactored old code, finished a milestone, finished practice assignment) "
    earned_bonus = STDIN.gets.chomp
    break if positive.include?(earned_bonus) || negative.include?(earned_bonus)
    puts "Possible answers: " + possible_bool_answers.to_s
  end
  earned_bonus = positive.include?(earned_bonus) ? true : false

  if earned_bonus
    puts "What did you do to earn a bonus?"
    bonuses.each do |key, value|
      puts "#{key} - #{value}"
    end

    bonus_xp = 0
    hours_for_bonus = 0

    loop do
      print "Answer: "
      bonus_key = STDIN.gets.chomp.to_i
      break if bonuses.keys.include?(bonus_key)
      puts "Please input a number of one of the tasks above!"
    end

    loop do
      print "How many hours? "
      hours_for_bonus = STDIN.gets.chomp
      break if hours_for_bonus.to_i.to_s == hours_for_bonus && hours_for_bonus.to_i > 0
      puts "Use positive integer!"
    end
    hours_for_bonus = hours_for_bonus.to_i
    bonus_xp = (hours_for_bonus * xp_per_hour * bonus_coefficient).to_i

  end

  xp_to_add = hours_worked * xp_per_hour
  if drank_water && enough_sleep && did_workout && did_meditation && ate_fruit_veg
    xp_to_add = (xp_to_add * 1.1).to_i
  end
  if earned_bonus
    xp_to_add += bonus_xp
  end

  data = read_from_db

  data["water"] = drank_water
  data["sleep"] = enough_sleep
  data["workout"] = did_workout
  data["meditation"] = did_meditation
  data["fruit_veg"] = ate_fruit_veg

  data["current_xp"] = data["current_xp"] + xp_to_add
  while data["current_xp"] >= data["next_lvl_xp"]
    data["current_lvl"] += 1
    data["current_lvl_xp"] = data["next_lvl_xp"]
    data["next_lvl_xp"] = get_next_lvl_xp(data["current_lvl"], data["current_lvl_xp"])
  end
  
  File.write("#{File.dirname(Pathname.new(__FILE__).realpath)}/db.txt", JSON.generate(data))
  print_char_sheet(read_from_db)

else
  puts "USAGE: gamify / gamify -add / gamify -milestone"
end